version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.11.4
    steps:
    - checkout
    - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
    - run:
        name: Install local dependencies
        command: npm install
    - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules
    # Lint the source code
    - run:
        name: Linting
        command: npm run lint
    # Build project with different configuration based on current branch
    - run:
        name: Building
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build-prod
          else
              npm run build-dev
          fi
    # Cache the dist folder
    - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRNACH }}-{{
          .Environment.CIRCLE_SHA1 }}
        paths:
          - dist

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
